### ISSUE TITLE
how to use it without CUDA

### ISSUE THREAD

**Issue by 0x00-pl** [tfzhou/C-HOI#10]
My target system has no CUDA and got this error:

>  OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

 mmdetection has CPU-only version `https://mmdetection.readthedocs.io/en/v2.2.0/install.html#install-with-cpu-only`

**Comment by tfzhou** [comment]
Hi, I have to say that I never ran the code in a CPU-only environment.
