### ISSUE TITLE
problem in checkpoint and datasets

### ISSUE THREAD

**Issue by zgplvyou** [tfzhou/C-HOI#11]
After setup the evironment and change some code, there are still two problems in checkpoints and datasets:
1. I convert test_2019.json to relations_all.json. however, relations_all.json can not comform the coco style, so I got the error
    cats = self.dataset['categories']
    KeyError: 'categories' 
2. I load checkpoint from hoiw_latest.pth, the model and loaded state dict do not match exactly, both sizes and keys. The error is
     size mismatch for reldn_head.freq_bias.rel_baseline.weight: copying a param with shape torch.Size([121, 11]) from checkpoint, the shape in current model is torch.Size([121, 12]).
size mismatch for reldn_head.prd_cls_feats.0.weight: copying a param with shape torch.Size([1024, 37632]) from checkpoint, the shape in current model is torch.Size([2048, 37632]).
size mismatch for reldn_head.prd_cls_feats.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for reldn_head.prd_cls_feats.2.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([2048, 2048]).
size mismatch for reldn_head.prd_cls_feats.2.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for reldn_head.prd_cls_scores.0.weight: copying a param with shape torch.Size([11, 1024]) from checkpoint, the shape in current model is torch.Size([11, 2048]).
size mismatch for reldn_head.prd_sbj_scores.0.weight: copying a param with shape torch.Size([11, 12544]) from checkpoint, the shape in current model is torch.Size([1024, 12544]).
size mismatch for reldn_head.prd_sbj_scores.0.bias: copying a param with shape torch.Size([11]) from checkpoint, the shape in current model is torch.Size([1024]).
size mismatch for reldn_head.prd_obj_scores.0.weight: copying a param with shape torch.Size([11, 12544]) from checkpoint, the shape in current model is torch.Size([1024, 12544]).
size mismatch for reldn_head.prd_obj_scores.0.bias: copying a param with shape torch.Size([11]) from checkpoint, the shape in current model is torch.Size([1024]).
missing keys in source state_dict: reldn_head.prd_sbj_scores.2.weight, reldn_head.prd_sbj_scores.2.bias, reldn_head.prd_obj_scores.2.weight, reldn_head.prd_obj_scores.2.bias, sa.g.conv.weight, sa.g.conv.bias, sa.theta.conv.weight, sa.theta.conv.bias, sa.phi.conv.weight, sa.phi.conv.bias, sa.conv_out.conv.weight, sa.conv_out.conv.bias

so anyone address these questions ? or we need the help from the author @tfzhou

**Comment by tfzhou** [comment]
please refer to the new code in the pytorch-1.5 branch. The problem has been addressed.
