### ISSUE TITLE
test error!!!

### ISSUE THREAD

**Issue by zhazhazhazhi** [tfzhou/C-HOI#2]
hello , I run the file .  hoiw datasets , I find the error about dataset in my file .

cats = self.dataset['categories']
KeyError: 'categories'

hoiw labels  format form  need to be transform the coco label ?

**Comment by stevenshen36** [comment]
I met the exact error!!!!
This is super annoying...

**Comment by tfzhou** [comment]
I guess this can be fixed with the provided json files.
