### ISSUE TITLE
hoiw_val.json

### ISSUE THREAD

**Issue by SISTMrL** [tfzhou/C-HOI#3]
hello, how wonderful the work is! when i run test, i encountered the error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/hoiw/annotations/hoiw_val.json'
what's the hoiw_val.json?

**Comment by lzg188** [comment]
me too

**Comment by yan-rui** [comment]
me too

**Comment by MeJerry215** [comment]
us too.

**Comment by yan-rui** [comment]
It seems like hoiw_val.json and hoiw_train.json are converted from trainval.json and match COCO object detection format?
@tfzhou

**Comment by ghost** [comment]
It seems the author do not care about the repo. [doge]

**Comment by tfzhou** [comment]
please refer to #8. I close this issue.
