### ISSUE TITLE
No such file or directory: 'pred_dist_overlap.npz'

### ISSUE THREAD

**Issue by juren1987** [tfzhou/C-HOI#6]
I run test_pic.py. It said No such file or directory: 'pred_dist_overlap.npz'. The problem is caused by codes in /C-HOI/mmdet/models/rel_heads/sparse_targets_rel.py at line 66. I check the code, it always load a file called "pred_dist_overlap.npz". I have no idea what this "pred_dist_overlap.npz" is. I cannot find it. Can anybody help me?

**Comment by wangy12** [comment]
> I run test_pic.py. It said No such file or directory: 'pred_dist_overlap.npz'. The problem is caused by codes in /C-HOI/mmdet/models/rel_heads/sparse_targets_rel.py at line 66. I check the code, it always load a file called "pred_dist_overlap.npz". I have no idea what this "pred_dist_overlap.npz" is. I cannot find it. Can anybody help me?

Hello, May I know how you resolve this problem? I'm also looking for 'pred_dist_overlap.npz' and 'pred_dist_overlap_hoiw.npz'
