### ISSUE TITLE
where is the hoiw datasets

### ISSUE THREAD

**Issue by zgplvyou** [tfzhou/C-HOI#8]
Hi, Mr Zhou, thanks for u contribution of this project. I try to achieve the script on HOIW dataset python tools/test_hoiw.py configs/hoiw/cascade_rcnn_x101_64x4d_fpn_1x_4gpu_rel.py hoiw_latest.pth --json_out det_result.json --hoiw_out hoiw_result.json
however, I cant find the det_result.json or hoiw_result.json in your google driver. In your driver, only three files are provided, hoiw_latest.pth, pic_latest.pth and pic_result.zip. So could u please provide the hoiw_result.zip with det_result.json and hoiw_result.json?

**Comment by wangy12** [comment]
Hey @zgplvyou `det-result.json` and `hoiw_result.json` are output files. Datasets are available here  http://www.picdataset.com/challenge/task/download/

**Comment by zgplvyou** [comment]
> Hey @zgplvyou `det-result.json` and `hoiw_result.json` are output files. Datasets are available here http://www.picdataset.com/challenge/task/download/

ok, thank u for the answer.

**Comment by zgplvyou** [comment]
@wangy12 Hi, wang, I download the dataset from the path. This project use customDataset, in the config file configs/hoiw/cascade_rcnn_x101_64x4d_fpn_1x_4gpu_rel.py, test path include ann_file=data_root + 'annotations/hoiw_val.json', rel_ann_file=data_root+'annotations/trainval.json'. now we can get the trainval.json from the downloading, so what is hoiw_val.json?

**Comment by lzg188** [comment]
i have the same question with zgplvyou

**Comment by wangy12** [comment]
`trainval.json` is in HOI-W dataset. I have the same issue with the other two json files. Let's see if @tfzhou will support: Can you please let us know where are `hoiw_train.json` and `hoiw_val.json`, or how to generate  @lzg188 @zgplvyou

**Comment by yan-rui** [comment]
m

**Comment by MeJerry215** [comment]
me too

**Comment by tfzhou** [comment]
Hi guys, hoiw_train.json and hoiw_val.json are converted from the original annotations of HOIW dataset. I am searching for the files or code, but it will take time for a three-years-ago project. Will back to you soon.

**Comment by tfzhou** [comment]
Please refer to the link in the updated readme for all json files I used. Thx.

**Comment by zgplvyou** [comment]
@tfzhou Hey, thank u for these files. I found the key is start from 'test_006539.jpg' to 'test_008793.gpg' in hoiw_test.json file, while it has 8,794 testing images. Of course, I can generate the extra keys as the format in hoiw_test.json.  
In fact we need to achieve the test mAP in your paper. when I load the hoiw_latest.pth, there are some keys mismatch, does it affect the final mAP or there is something wrong in my project?
