### ISSUE TITLE
Where can I get "pred_dist_overlap_hoiw.npz"

### ISSUE THREAD

**Issue by stevenshen36** [tfzhou/C-HOI#9]

**Comment by wangy12** [comment]
@tfzhou Help needed. Thx

**Comment by tfzhou** [comment]
Hi, probably this file is for you: https://github.com/tfzhou/C-HOI/blob/master/mmdet/models/rel_heads/sparse_targets_rel.py

**Comment by MeJerry215** [comment]
@tfzhou https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/sparse_targets_rel.py#L66  here loads pred_dist_overlap_hoiw.npz file, but how to generate this file? or how to get it.

**Comment by tfzhou** [comment]
Hi, would the file be created automatically from here: https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/sparse_targets_rel.py#L64

**Comment by MeJerry215** [comment]
I saw the only using of FrequencyBias is in https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/reldn_head.py#L38,
It only pass `must_overlap` and `mode`.
How to set rel_ann_file, num_prd_class and num_class if using HOIW datasets?

**Comment by MeJerry215** [comment]
> I saw the only using of FrequencyBias is in
> 
> https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/reldn_head.py#L38
> 
> ,
> It only pass `must_overlap` and `mode`.
> How to set rel_ann_file, num_prd_class and num_class if using HOIW datasets?

hey @tfzhou, does the trainval.json loaded  have been processed ?

https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/get_dataset_counts_rel.py#L47

the trainval.json does't contains the key word `predicate`, `subject`, `bbox`, etc

**Comment by MeJerry215** [comment]
> > I saw the only using of FrequencyBias is in
> > https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/reldn_head.py#L38
> > 
> > ,
> > It only pass `must_overlap` and `mode`.
> > How to set rel_ann_file, num_prd_class and num_class if using HOIW datasets?
> 
> hey @tfzhou, does the trainval.json loaded have been processed ?
> 
> https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/get_dataset_counts_rel.py#L47
> 
> the trainval.json does't contains the key word `predicate`, `subject`, `bbox`, etc

https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/tools/convert_hoiw_anno_to_vg_format.py#L88 I find it.

**Comment by zgplvyou** [comment]
> > > I saw the only using of FrequencyBias is in
> > > https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/reldn_head.py#L38
> > > 
> > > ,
> > > It only pass `must_overlap` and `mode`.
> > > How to set rel_ann_file, num_prd_class and num_class if using HOIW datasets?
> > 
> > 
> > hey @tfzhou, does the trainval.json loaded have been processed ?
> > https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/mmdet/models/rel_heads/get_dataset_counts_rel.py#L47
> > 
> > the trainval.json does't contains the key word `predicate`, `subject`, `bbox`, etc
> 
> https://github.com/tfzhou/C-HOI/blob/200fb9254f572af2745aabd11af544d6258b3f51/tools/convert_hoiw_anno_to_vg_format.py#L88
> 
> I find it.

this file seems can not transform hoiw.json to coco style json.

**Comment by tfzhou** [comment]
I have uploaded the npz files in case you cannot generate it from the code.

**Comment by zgplvyou** [comment]
> I have uploaded the npz files in case you cannot generate it from the code.

Hey, @tfzhou thank u for these files, factly, we wanna achieve the 66.04% mAP in your paper on test dataset. however, I only achieve 61% mAP. maybe something wrong in the checkpoint. when I load the hoiw_latest.pt, the dimension is mismatch in https://github.com/tfzhou/C-HOI/blob/65c1842ff8184e5c9b36385d33d7389dfe31463e/mmdet/models/rel_heads/reldn_head.py#L41 the demension is 2048 in the network, while 1024 in the checkponit. All the mismatch are in ReldnHead layer. I think maybe the mismatch cause my lower result, so how can I solve this problem?

**Comment by Xihe-Gao** [comment]
> > I have uploaded the npz files in case you cannot generate it from the code.
> 
> Hey, @tfzhou thank u for these files, factly, we wanna achieve the 66.04% mAP in your paper on test dataset. however, I only achieve 61% mAP. maybe something wrong in the checkpoint. when I load the hoiw_latest.pt, the dimension is mismatch in
> 
> https://github.com/tfzhou/C-HOI/blob/65c1842ff8184e5c9b36385d33d7389dfe31463e/mmdet/models/rel_heads/reldn_head.py#L41
> 
> the demension is 2048 in the network, while 1024 in the checkponit. All the mismatch are in ReldnHead layer. I think maybe the mismatch cause my lower result, so how can I solve this problem?

May I ask where you found the annotations of test dataset? Thanks.

**Comment by HawkL327** [comment]
> 

Are you guys using the params in the config file? I notice that the current config file uses validation file to do test. After I run the program, the MAP was super high like 0.791

**Comment by HawkL327** [comment]
> 

Are you guys using params in config file? I notice that the test dataset in config file is hoiw_val.json. After I run the program, the MAP was higher than pape, like 0.791

**Comment by tfzhou** [comment]
Hi, our results on the test set is obtained by submitting results into the evaluation platform of ICCV19 PIC Challenge. In our paper, we directly compare with other challenge submissions. The released model is the best single model that I obtained, but the final results in the challenge, if I remember correctly, are obtained by model ensemble.  For the dimension issue, please use 1024.

**Comment by zgplvyou** [comment]
> Hi, our results on the test set is obtained by submitting results into the evaluation platform of ICCV19 PIC Challenge. In our paper, we directly compare with other challenge submissions. The released model is the best single model that I obtained, but the final results in the challenge, if I remember correctly, are obtained by model ensemble. For the dimension issue, please use 1024.

I have tried change the dimension into 1024. however, the weight don`t contain the keys of so_core https://github.com/tfzhou/C-HOI/blob/65c1842ff8184e5c9b36385d33d7389dfe31463e/mmdet/models/rel_heads/reldn_head.py#L60 . I tried to remove it, but the result was still 60%.

**Comment by HawkL327** [comment]
@zgplvyou Hi，you have done a great work ！！！how did you get 60%？Did you change any parameter？

**Comment by zgplvyou** [comment]
> @zgplvyou Hi，you have done a great work ！！！how did you get 60%？Did you change any parameter？

u need to change the config file

**Comment by Xihe-Gao** [comment]
> > @zgplvyou Hi，you have done a great work ！！！how did you get 60%？Did you change any parameter？
> 
> u need to change the config file

So, the 60% results that you got is on validation dataset, or test dataset? As far as I know, the annotations of test dataset are not provided for download on PIC website.

**Comment by tfzhou** [comment]
Hi @all, I have created a new branch "pytorch-1.5", and have attempted to run the evaluation on HOIW test set. Please refer to README for more details. The evaluation costs time, and I will expect to report my scores in the coming few days. 

p.s. But limited by the gpu memory, I can only run evaluation with small-size inputs, like (1200,700). You can try a larger size (1600, 1200) to obtain better performance. 

p.s.s. I did not make the code run on A100. I guess it is due to the old version of mmcv. I will not see the issue at the moment.

**Comment by HawkL327** [comment]
@tfzhou Hi，Dr.Zhou, could you please upload the test_2019.json file? Thank you !

**Comment by tfzhou** [comment]
please see README. I will close this issue now, but feel free to reopen it if you encounter other problems.
